name: Deploy Lambda to S3

on:
  push:
    paths:
      - 'services/user-service-lambda/**'
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd services/user-service-lambda
          npm install

      - name: Zip Lambda function
        run: |
          cd services/user-service-lambda
          zip -r $GITHUB_WORKSPACE/services/user-service-lambda/lambda-code.zip .

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Upload Lambda code to S3
        run: |
          aws s3 cp $GITHUB_WORKSPACE/services/user-service-lambda/lambda-code.zip s3://${{ vars.TMS_BUCKET_NAME }}/${{ vars.USER_SERVICE_LAMBDA_FUNCTION_NAME }}

      - name: Remove local ZIP file
        run: rm $GITHUB_WORKSPACE/services/user-service-lambda/lambda-code.zip